### ISSUE TITLE
Safari doesn't work

### ISSUE THREAD

**Issue by paullauyc** [JsDaddy/ngx-loader-indicator#11]
Safari Error:
TypeError: t.animate is not a function. (In 't.animate([{transform:"rotate(360deg)"},{transform:"rotate(0deg)"}],this.rotateAnimaitioan)', 't.animate' is undefined)

**Comment by Nabelops** [comment]
+1

**Comment by NepipenkoIgor** [comment]
@paullauyc @Nabelops  Seems like it is outdated
